# 异常处理方式

1. try catch finally
2. throws

## try catch
> 类似于 if 语句

```text
如果异常没有出现,则执行 try 块

如果异常出现则执行 catch 块
```

```java
File f = new File("D:/没有的文件.txt");
try {
    FileInputStream fis = new FileInputStream(f);
    System.out.println(fis + "打开文件成功");
} catch (FileNotFoundException e) {
    e.printStackTrace();
}
```
> 使用 父类 Exception 也可以当做 catch 条件

## 多异常捕捉
> 多个 catch

* 如果一个语句会抛出多个异常,可以进行多 catch
```java
File f = new File("D:/不存在的文件.txt");
try {
    new FileInputStream(f);
    Date d = sdf.parse("2020-23-23");
} catch (FileNotFoundException e) {
    System.out.println("文件打开异常");
    e.printStackTrace();
} catch (ParseException e1) {
    System.out.println("时间解析异常");
    e.printStrackTrace();
}
```

* 多个异常同时 catch
```java
catch (FileNotFoundException | ParseException e) {
    // 可以使用 instanceof 进行判断
    if (e instanceof FileNotFoundException) {
        System.out.println("文件不存在异常");
    }
    if (e instanceof ParseException) {
        System.out.println("解析异常");
    }
}
```

## throws
> 抛出异常

```text
一个方法不想捕捉处理异常

则 throws 抛出异常

如果此方法被调用,则如上,要么捕捉异常,要么抛出
```
> 在方法后使用 throws 关键字

```java
public static void main(String[] args) throws FileNotFoundException {
    File f = new File("D:/文件不存在.txt");
    new FileInputStream(f);
}
```

## finally
> 不论是否异常,都会执行

```java
catch (FileNotFoundException | ParseException e) {
    // 可以使用 instanceof 进行判断
    if (e instanceof FileNotFoundException) {
        System.out.println("文件不存在异常");
    }
    if (e instanceof ParseException) {
        System.out.println("解析异常");
    }
} finally {
    // 无论如何都会执行
    System.out.println("执行 finally 语句");
}
```

## throws 与 throw 的区别
> 执行 throw 抛出异常

1. throws 出现在方法声明,throw 出现在方法体
2. throws 表示出现异常的可能性 throw 执行则一定抛出了某个异常对象

# 练习 异常处理

```text
假设有一个方法 public int method()， 会返回一个整数
在这个方法中有try catch 和 finally.
try 里返回 1
catch 里 返回 2
finally 里 返回3
那么，这个方法到底返回多少？ 
```

## 答案
> 一定是返回 3
>> 一定回执行 finally